### ISSUE TITLE
Bug/numbers doesn't build on Elixir 1.19

### ISSUE THREAD

**Issue by daidoji** [Qqwy/elixir-number#51]
It looks like this doesn't build on Elixir 1.19.

```
daidoji@vLEIDALaptop1:~/vLEIDA/elixir-number$ mix compile
    warning: use Mix.Config is deprecated. Use the Config module instead
    │
  3 │ use Mix.Config
    │ ~~~~~~~~~~~~~~
    │
    └─ config/config.exs:3

Compiling 7 files (.ex)

== Compilation error in file lib/numbers/implementations/float.ex ==
** (Coerce.CompileError) `Coerce.defcoercion` implementation does not implement `coerce/2`.
    lib/numbers/implementations/float.ex:40: (file)
    (elixir 1.19.0) lib/kernel/parallel_compiler.ex:483: anonymous fn/5 in Kernel.ParallelCompiler.spawn_workers/8

daidoji@vLEIDALaptop1:~/vLEIDA/elixir-number$ erl --version
Erlang/OTP 28 [erts-16.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

^Cdaidoji@vLEIDALaptop1:~/vLEIDA/elixir-number$ elixir --version
Erlang/OTP 28 [erts-16.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]

Elixir 1.19.0 (compiled with Erlang/OTP 26)
```

**Comment by daidoji** [comment]
Oh nevermind, looks like this should be resolved as soon as https://github.com/Qqwy/elixir-coerce/pull/43 is merged and the dependency is updated.

**Comment by Qqwy** [comment]
With the new version of `coerce` that was released a while back, this issue should be solved.
